-- OsorIA landing migration into Databases4OsorIA (feqsjdhcsrksvrfsjsfv)
-- Source project: yudejamenhxzipvdjrxq (landing, schema public)
-- Target schema: "landingOsorIA"
--
-- El nombre del schema lleva mayusculas, igual que OsoriaEccomerse / OsoIADataAnalisis
-- en este mismo proyecto, asi que siempre va entre comillas dobles.

create schema if not exists "landingOsorIA";

grant usage on schema "landingOsorIA" to anon, authenticated, service_role;

-- ============================================================
-- 1. Tablas que hoy viven en public del proyecto viejo
-- ============================================================

create table if not exists "landingOsorIA".users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_login timestamptz,
  plan text not null default 'free',
  subscription_status text not null default 'inactive',
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_period_start timestamptz,
  subscription_period_end timestamptz,
  shopify_domain text,
  shopify_admin_api_token text,
  shopify_storefront_api_token text,
  shopify_theme_id text,
  shopify_api_key text,
  shopify_secret_key text
);

create index if not exists idx_users_email on "landingOsorIA".users (email);
create index if not exists idx_users_plan on "landingOsorIA".users (plan);
create index if not exists idx_users_subscription_status on "landingOsorIA".users (subscription_status);
create index if not exists idx_users_stripe_customer_id on "landingOsorIA".users (stripe_customer_id);
create index if not exists idx_users_shopify_domain on "landingOsorIA".users (shopify_domain);

create table if not exists "landingOsorIA".contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  idea text not null,
  status text not null default 'nuevo',
  created_at timestamptz not null default now()
);

create index if not exists idx_contact_messages_created_at on "landingOsorIA".contact_messages (created_at desc);
create index if not exists idx_contact_messages_status on "landingOsorIA".contact_messages (status);

create table if not exists "landingOsorIA".chat_sessions (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  message_count integer not null default 0,
  last_message_at timestamptz,
  whatsapp_sent boolean not null default false,
  whatsapp_sent_at timestamptz
);

create index if not exists idx_chat_sessions_created_at on "landingOsorIA".chat_sessions (created_at);
create index if not exists idx_chat_sessions_whatsapp_sent on "landingOsorIA".chat_sessions (whatsapp_sent);
create index if not exists idx_chat_sessions_last_message_at on "landingOsorIA".chat_sessions (last_message_at);

create table if not exists "landingOsorIA".chat_conversations (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_conversations_session_id on "landingOsorIA".chat_conversations (session_id);
create index if not exists idx_chat_conversations_created_at on "landingOsorIA".chat_conversations (created_at);

-- search_path fijo: sin esto el linter de Supabase lo marca como mutable.
create or replace function "landingOsorIA".set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_chat_sessions_updated_at on "landingOsorIA".chat_sessions;
create trigger trg_chat_sessions_updated_at
  before update on "landingOsorIA".chat_sessions
  for each row execute function "landingOsorIA".set_updated_at();

drop trigger if exists trg_users_updated_at on "landingOsorIA".users;
create trigger trg_users_updated_at
  before update on "landingOsorIA".users
  for each row execute function "landingOsorIA".set_updated_at();

-- ============================================================
-- 2. Datos de GitHub que alimentan la landing
-- ============================================================

-- Un registro por repositorio de la cuenta sincronizada.
create table if not exists "landingOsorIA".github_repos (
  id bigint primary key,                    -- databaseId de GitHub
  node_id text not null unique,
  owner text not null,
  name text not null,
  full_name text not null unique,
  description text,
  html_url text not null,
  homepage text,
  is_private boolean not null default true,
  is_fork boolean not null default false,
  is_archived boolean not null default false,
  primary_language text,
  languages jsonb not null default '{}'::jsonb,
  topics text[] not null default '{}',
  stargazers integer not null default 0,
  forks integer not null default 0,
  default_branch text,
  commit_count integer not null default 0,  -- commits en la rama por defecto
  repo_created_at timestamptz,
  pushed_at timestamptz,

  -- Control editorial de la seccion publica de la landing.
  -- Se autogenera desde el repo, pero un repo privado nunca se publica solo.
  is_published boolean not null default false,
  display_name text,
  display_summary text,
  sort_order integer not null default 0,

  synced_at timestamptz not null default now()
);

create index if not exists idx_github_repos_published on "landingOsorIA".github_repos (is_published, sort_order, pushed_at desc);
create index if not exists idx_github_repos_pushed_at on "landingOsorIA".github_repos (pushed_at desc);

-- Contribuciones por año: la API de GitHub solo entrega ventanas de 1 año,
-- asi que el total se arma sumando estas filas.
create table if not exists "landingOsorIA".github_yearly_contributions (
  owner text not null,
  year integer not null,
  total_commit_contributions integer not null default 0,
  restricted_contributions integer not null default 0,
  synced_at timestamptz not null default now(),
  primary key (owner, year)
);

-- Foto agregada para que la landing lea una sola fila.
create table if not exists "landingOsorIA".github_stats_snapshots (
  id bigint generated by default as identity primary key,
  owner text not null,
  captured_at timestamptz not null default now(),
  total_commits integer not null default 0,
  total_repos integer not null default 0,
  public_repos integer not null default 0,
  private_repos integer not null default 0,
  total_stars integer not null default 0,
  languages jsonb not null default '{}'::jsonb,
  first_activity_at timestamptz
);

create index if not exists idx_github_stats_snapshots_captured on "landingOsorIA".github_stats_snapshots (owner, captured_at desc);

create table if not exists "landingOsorIA".github_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running', 'ok', 'error')),
  repos_synced integer not null default 0,
  total_commits integer not null default 0,
  error_message text
);

create index if not exists idx_github_sync_runs_started on "landingOsorIA".github_sync_runs (started_at desc);

-- ============================================================
-- 3. RLS
-- ============================================================

alter table "landingOsorIA".users enable row level security;
alter table "landingOsorIA".contact_messages enable row level security;
alter table "landingOsorIA".chat_sessions enable row level security;
alter table "landingOsorIA".chat_conversations enable row level security;
alter table "landingOsorIA".github_repos enable row level security;
alter table "landingOsorIA".github_yearly_contributions enable row level security;
alter table "landingOsorIA".github_stats_snapshots enable row level security;
alter table "landingOsorIA".github_sync_runs enable row level security;

-- users, contact_messages y chat_* solo se tocan con service_role desde el
-- servidor de Next. Sin politicas para anon: quedan cerradas por defecto.

-- Los agregados de GitHub son publicos a proposito: son el contador de la landing.
drop policy if exists "public read github stats" on "landingOsorIA".github_stats_snapshots;
create policy "public read github stats"
  on "landingOsorIA".github_stats_snapshots
  for select to anon, authenticated using (true);

drop policy if exists "public read github years" on "landingOsorIA".github_yearly_contributions;
create policy "public read github years"
  on "landingOsorIA".github_yearly_contributions
  for select to anon, authenticated using (true);

-- De los repos solo sale lo publicado Y publico. Un repo privado nunca se
-- expone aunque alguien marque is_published por error.
drop policy if exists "public read published public repos" on "landingOsorIA".github_repos;
create policy "public read published public repos"
  on "landingOsorIA".github_repos
  for select to anon, authenticated using (is_published and not is_private);

-- ============================================================
-- 4. Grants
-- ============================================================

grant all on all tables in schema "landingOsorIA" to service_role;
grant all on all sequences in schema "landingOsorIA" to service_role;
grant select on
  "landingOsorIA".github_repos,
  "landingOsorIA".github_stats_snapshots,
  "landingOsorIA".github_yearly_contributions
  to anon, authenticated;
grant execute on all functions in schema "landingOsorIA" to service_role;

alter default privileges in schema "landingOsorIA"
  grant all on tables to service_role;
alter default privileges in schema "landingOsorIA"
  grant all on sequences to service_role;
